{{ config(materialized='table') }}

SELECT
    /* === BACKTEST COLUMNS (from your union) === */
    b.PARAMETERID,
    b.UNIVERSALPARAMETERID,
    b.VACOMPANYID,
    b.PERIOD,
    b.CALENDARPERIOD,
    b.PERIODTYPE,
    b.VALUE,
    b.CURRENT_YEAR,
    b.NEXT_YEAR,
    b.DTYPE,

    /* === PERIOD META COLUMNS (prefix to avoid collisions) === */
    b.PERIODFREQUENCYTYPE           AS PM_PERIODFREQUENCYTYPE,
    b.ISREPORTED                    AS PM_ISREPORTED,
    b.EXACTPERIODENDDATE            AS PM_EXACTPERIODENDDATE,
    b.EARNINGSDATE                  AS PM_EARNINGSDATE,
    b.EARNINGSANNOUNCEMENTTIMING    AS PM_EARNINGS_ANNOUNCEMENT_TIMING,
    b.RELATIVEPERIOD                AS PM_RELATIVEPERIOD,

    /* === COMPANY META COLUMNS (already prefixed) === */
    m.VATICKER                      AS META_VATICKER,
    m.BLOOMBERGTICKER               AS META_BLOOMBERG_TICKER,
    m.FIGICOMPANY                   AS META_FIGI_COMPANY,
    m.FIGIINSTRUMENT                AS META_FIGI_INSTRUMENT,
    m.FACTSETENTITYID               AS META_FACTSET_ENTITYID,
    m.CIK                           AS META_CIK,
    m.LEI                           AS META_LEI,
    m.COMPANYNAME                   AS META_COMPANY_NAME,
    m.COMPANYLEGALNAME              AS META_COMPANY_LEGAL_NAME,
    m.FISCALYEARENDMONTH            AS META_FISCALYEARENDMONTH,
    m.FISCALYEAREND                 AS META_FISCALYEAREND,
    m.BASECURRENCY                  AS META_BASECURRENCY,
    m.BASEREPORTINGPERIOD           AS META_BASEREPORTINGPERIOD,
    m.STATUSID                      AS META_STATUSID,
    m.PRIMARYEXCHANGECURRENCY       AS META_PRIMARYEXCHANGECURRENCY,
    m.PRIMARYEXCHANGECODE           AS META_PRIMARYEXCHANGECODE,
    m.PRIMARYEXCHANGENAME           AS META_PRIMARYEXCHANGENAME,
    m.COUNTRYOFDOMICILE             AS META_COUNTRYOFDOMICILE,
    m.ISOCOUNTRYCODE                AS META_ISOCOUNTRYCODE,
    m.VASECTORID                    AS META_VASECTORID,
    m.VAINDUSTRYID                  AS META_VAINDUSTRYID,
    m.VACOUNTRYID                   AS META_VACOUNTRYID,
    m.VAREGIONID                    AS META_VAREGIONID,
    m.NEXTESTIMATEDEARNINGSDATE     AS META_NEXT_EARNINGS_DATE,
    m.ISACTIVE                      AS META_ISACTIVE,
    m.ISMODELSONLY                  AS META_ISMODELSONLY,
    m.ISACQUIRED                    AS META_ISACQUIRED,
    m.HASCONSENSUS                  AS META_HASCONSENSUS,
    m.MODELSTARTDATE                AS META_MODELSTARTDATE,
    m.FIRSTAVAILABLEDATE            AS META_FIRSTAVAILABLEDATE,
    m.COVERAGEENDDATE               AS META_COVERAGEENDDATE,
    m.INCLUDEDINCONSENSUSON         AS META_INCLUDED_IN_CONSENSUS_ON,
    m.PROCESSEDMODELDATE            AS META_PROCESSED_MODEL_DATE,
    m.CONSENSUSCALCULATEDON         AS META_CONSENSUS_CALCULATED_ON,
    m.DISPLAYSCALEID                AS META_DISPLAYSCALEID,
    m.TEMPLATEID                    AS META_TEMPLATEID,
    m.CAPIQCID                      AS META_CAPIQCID

FROM {{ ref('backtest') }} b
LEFT JOIN {{ ref('va_company_meta') }} m
    ON b.VACOMPANYID = m.VACOMPANYID