{{ config(materialized='table') }}

WITH ce AS (
    SELECT
        SYMBOL AS CE_SYMBOL,
        SEGMENT_NAME AS CE_SEGMENT_NAME,
        PERIOD AS CE_CALENDAR_QUARTER,
        PERIOD_START_DT::DATE AS CE_PERIOD_START_DT,
        PTD_END_DT::DATE AS CE_PTD_END_DT,
        PARTIAL_PERIOD_FLAG AS CE_PARTIAL_PERIOD_FLAG,
        PERIOD_TYPE AS CE_PERIOD_TYPE,
        YA_PERIOD AS CE_YA_PERIOD,
        PTD_SPEND_USD_YOY AS CE_PTD_SPEND_USD_YOY,
        PTD_TRANS_YOY AS CE_PTD_TRANS_YOY,
        VERSION AS CE_VERSION,
        TRANS_COUNT AS CE_TRANS_COUNT,
        SPEND_AMOUNT_USD AS CE_SPEND_AMOUNT_USD
    FROM DBT_CLOUD_DB.MODELS.ce_1_2_historical
),

bt AS (
    SELECT
        BT_SYMBOL,
        CALENDARPERIOD_RAW,
        CALENDAR_QUARTER_MAPPING,

        -- explicitly list BT columns you want to bring in
        PARAMETERID,
        UNIVERSALPARAMETERID,
        VACOMPANYID,
        PERIOD,
        CALENDARPERIOD,
        PERIODTYPE,
        VALUE,
        CURRENT_YEAR,
        NEXT_YEAR,
        DTYPE,
        PM_PERIODFREQUENCYTYPE,
        PM_ISREPORTED,
        PM_EXACTPERIODENDDATE,
        PM_EARNINGSDATE,
        PM_EARNINGS_ANNOUNCEMENT_TIMING,
        PM_RELATIVEPERIOD,
        META_VATICKER,
        META_BLOOMBERG_TICKER,
        META_FIGI_COMPANY,
        META_FIGI_INSTRUMENT,
        META_FACTSET_ENTITYID,
        META_CIK,
        META_LEI,
        META_COMPANY_NAME,
        META_COMPANY_LEGAL_NAME,
        META_FISCALYEARENDMONTH,
        META_FISCALYEAREND,
        META_BASECURRENCY,
        META_BASEREPORTINGPERIOD,
        META_STATUSID,
        META_PRIMARYEXCHANGECURRENCY,
        META_PRIMARYEXCHANGECODE,
        META_PRIMARYEXCHANGENAME,
        META_COUNTRYOFDOMICILE,
        META_ISOCOUNTRYCODE,
        META_VASECTORID,
        META_VAINDUSTRYID,
        META_VACOUNTRYID,
        META_VAREGIONID,
        META_NEXT_EARNINGS_DATE,
        META_ISACTIVE,
        META_ISMODELSONLY,
        META_ISACQUIRED,
        META_HASCONSENSUS,
        META_MODELSTARTDATE,
        META_FIRSTAVAILABLEDATE,
        META_COVERAGEENDDATE,
        META_INCLUDED_IN_CONSENSUS_ON,
        META_PROCESSED_MODEL_DATE,
        META_CONSENSUS_CALCULATED_ON,
        META_DISPLAYSCALEID,
        META_TEMPLATEID,
        META_CAPIQCID,
        CALENDAR_QUARTER_END_DATE
    FROM DBT_CLOUD_DB.MODELS.backtest_final
)

SELECT
    ce.*,
    bt.*
FROM ce
LEFT JOIN bt
  ON ce.CE_SYMBOL = bt.BT_SYMBOL
 AND ce.CE_CALENDAR_QUARTER = bt.CALENDAR_QUARTER_MAPPING

ORDER BY ce.CE_SYMBOL, ce.CE_CALENDAR_QUARTER


