{{ config(materialized='table') }}

SELECT
    PARAMETERID,
    UNIVERSALPARAMETERID,
    VACOMPANYID,
    PERIOD,
    CALENDARPERIOD,
    PERIODTYPE,
    VALUE,
    EXTRACT(YEAR FROM CURRENT_DATE()) AS CURRENT_YEAR,
    EXTRACT(YEAR FROM CURRENT_DATE()) + 1 AS NEXT_YEAR,
    'ACTUALS' AS DTYPE
FROM {{ source('va', 'vaactuals_v2_latest') }}
WHERE UNIVERSALPARAMETERID = '4435'